-- MySQL Script generated by MySQL Workbench
-- vie 08 oct 2021 21:00:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoRevistas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoRevistas` ;

-- -----------------------------------------------------
-- Schema ProyectoRevistas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoRevistas` ;
USE `ProyectoRevistas` ;

-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Persona` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `foto` LONGBLOB NULL,
  `hobbies` VARCHAR(75) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Categoria` (
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Revista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Revista` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Revista` (
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `pago` TINYINT NOT NULL,
  `costo_suscripcion` DOUBLE NULL,
  `costo_dia` DOUBLE NULL,
  `nombre_categoria` VARCHAR(40) NOT NULL,
  `id_editor` INT NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_Revista_Persona1_idx` (`id_editor` ASC) VISIBLE,
  INDEX `fk_Revista_Categoria1_idx` (`nombre_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Revista_Persona1`
    FOREIGN KEY (`id_editor`)
    REFERENCES `ProyectoRevistas`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revista_Categoria1`
    FOREIGN KEY (`nombre_categoria`)
    REFERENCES `ProyectoRevistas`.`Categoria` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Anunciante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Anunciante` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Anunciante` (
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Anuncio` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Anuncio` (
  `id` INT NOT NULL,
  `tipo_anuncio` INT NOT NULL,
  `texto_anuncio` VARCHAR(200) NULL,
  `foto_anuncio` LONGBLOB NULL,
  `link_video` VARCHAR(60) NULL,
  `costo` DOUBLE NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_expiracion` DATE NOT NULL,
  `nombre_anunciante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Anuncio_Anunciante1_idx` (`nombre_anunciante` ASC) VISIBLE,
  CONSTRAINT `fk_Anuncio_Anunciante1`
    FOREIGN KEY (`nombre_anunciante`)
    REFERENCES `ProyectoRevistas`.`Anunciante` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Publicacion` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Publicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` LONGBLOB NOT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `nombre_revista` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Publicacion_Revista_idx` (`nombre_revista` ASC) VISIBLE,
  CONSTRAINT `fk_Publicacion_Revista`
    FOREIGN KEY (`nombre_revista`)
    REFERENCES `ProyectoRevistas`.`Revista` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Etiqueta` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Etiqueta` (
  `nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Preferencias_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Preferencias_Usuario` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Preferencias_Usuario` (
  `nombre_etiqueta` VARCHAR(30) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`nombre_etiqueta`, `id_usuario`),
  INDEX `fk_Preferencias_Usuario_Etiqueta1_idx` (`nombre_etiqueta` ASC) VISIBLE,
  INDEX `fk_Preferencias_Usuario_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Preferencias_Usuario_Etiqueta1`
    FOREIGN KEY (`nombre_etiqueta`)
    REFERENCES `ProyectoRevistas`.`Etiqueta` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preferencias_Usuario_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProyectoRevistas`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Etiquetas_Revista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Etiquetas_Revista` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Etiquetas_Revista` (
  `nombre_revista` VARCHAR(50) NOT NULL,
  `nombre_etiqueta` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nombre_revista`, `nombre_etiqueta`),
  INDEX `fk_Etiquetas_Revista_Revista1_idx` (`nombre_revista` ASC) VISIBLE,
  INDEX `fk_Etiquetas_Revista_Etiqueta1_idx` (`nombre_etiqueta` ASC) VISIBLE,
  CONSTRAINT `fk_Etiquetas_Revista_Revista1`
    FOREIGN KEY (`nombre_revista`)
    REFERENCES `ProyectoRevistas`.`Revista` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etiquetas_Revista_Etiqueta1`
    FOREIGN KEY (`nombre_etiqueta`)
    REFERENCES `ProyectoRevistas`.`Etiqueta` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Comentario` (
  `id` INT NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  `fecha_comentario` DATE NOT NULL,
  `nombre_revista` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comentario_Revista1_idx` (`nombre_revista` ASC) VISIBLE,
  INDEX `fk_Comentario_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_Revista1`
    FOREIGN KEY (`nombre_revista`)
    REFERENCES `ProyectoRevistas`.`Revista` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProyectoRevistas`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Suscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Suscripcion` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Suscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_suscripcion` DATE NOT NULL,
  `fecha_caducidad` DATE NULL,
  `nombre_revista` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Suscripcion_Revista1_idx` (`nombre_revista` ASC) VISIBLE,
  INDEX `fk_Suscripcion_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Suscripcion_Revista1`
    FOREIGN KEY (`nombre_revista`)
    REFERENCES `ProyectoRevistas`.`Revista` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suscripcion_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProyectoRevistas`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Me_Gusta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Me_Gusta` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Me_Gusta` (
  `nombre_revista` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`nombre_revista`, `id_usuario`),
  INDEX `fk_Like_Usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Like_Revista1`
    FOREIGN KEY (`nombre_revista`)
    REFERENCES `ProyectoRevistas`.`Revista` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProyectoRevistas`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Etiquetas_Anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Etiquetas_Anuncio` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Etiquetas_Anuncio` (
  `Etiqueta_nombre` VARCHAR(30) NOT NULL,
  `Anuncio_id` INT NOT NULL,
  PRIMARY KEY (`Etiqueta_nombre`, `Anuncio_id`),
  INDEX `fk_Etiquetas_Anuncio_Anuncio1_idx` (`Anuncio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Etiquetas_Anuncio_Etiqueta1`
    FOREIGN KEY (`Etiqueta_nombre`)
    REFERENCES `ProyectoRevistas`.`Etiqueta` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etiquetas_Anuncio_Anuncio1`
    FOREIGN KEY (`Anuncio_id`)
    REFERENCES `ProyectoRevistas`.`Anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Cambio_Costo_Diario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Cambio_Costo_Diario` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Cambio_Costo_Diario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha_cambio` DATE NOT NULL,
  `nombre_revista` VARCHAR(50) NOT NULL,
  INDEX `fk_Costo_Diario_Revista1_idx` (`nombre_revista` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Costo_Diario_Revista1`
    FOREIGN KEY (`nombre_revista`)
    REFERENCES `ProyectoRevistas`.`Revista` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Valores_Global`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Valores_Global` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Valores_Global` (
  `porcentaje_ganancia` INT NOT NULL,
  `costo_anuncio_texto` DOUBLE NOT NULL,
  `costo_anuncio_imagen` DOUBLE NOT NULL,
  `costo_anuncio_video` DOUBLE NOT NULL,
  PRIMARY KEY (`porcentaje_ganancia`, `costo_anuncio_texto`, `costo_anuncio_imagen`, `costo_anuncio_video`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Pago` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `id_suscripcion` INT NOT NULL,
  INDEX `fk_Pago_Suscripcion1_idx` (`id_suscripcion` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pago_Suscripcion1`
    FOREIGN KEY (`id_suscripcion`)
    REFERENCES `ProyectoRevistas`.`Suscripcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Contador_Anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Contador_Anuncio` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Contador_Anuncio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `URL_pagina` VARCHAR(60) NOT NULL,
  `id_anuncio` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Contador_Anuncio_Anuncio1_idx` (`id_anuncio` ASC) VISIBLE,
  CONSTRAINT `fk_Contador_Anuncio_Anuncio1`
    FOREIGN KEY (`id_anuncio`)
    REFERENCES `ProyectoRevistas`.`Anuncio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoRevistas`.`Categorias_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoRevistas`.`Categorias_Usuario` ;

CREATE TABLE IF NOT EXISTS `ProyectoRevistas`.`Categorias_Usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_categoria` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_usuario`, `nombre_categoria`),
  INDEX `fk_Categorias_Usuario_Categoria1_idx` (`nombre_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_Usuario_Persona1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ProyectoRevistas`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categorias_Usuario_Categoria1`
    FOREIGN KEY (`nombre_categoria`)
    REFERENCES `ProyectoRevistas`.`Categoria` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
